version: 2.1

executors:
  docker:
    docker:
      - image: circleci/node:14  
    working_directory: ~/repo

jobs:
  sonar-scanner:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout  # Check out your repository
      - run:
          name: Install SonarQube Scanner
          command: |
            curl -sS https://downloads.sonarsource.com/sonarqube-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
            unzip sonar-scanner.zip
            export PATH=$PATH:~/sonar-scanner-4.6.2.2472-linux/bin
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey= SonerKey \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN  1e3abfc693ba3fe7d1d9135797dae8a2cd7077f7
              -Dsonar.projectBaseDir= .

workflows:
  version: 2
  build_and_scan:
    jobs:
      - sonar-scanner
